.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. kenfmcoin_qt test_kenfmcoin_qt
clean: FORCE
	$(MAKE) -C .. kenfmcoin_qt_clean test_kenfmcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_kenfmcoin_qt_check
kenfmcoin-qt kenfmcoin-qt.exe: FORCE
	 $(MAKE) -C .. kenfmcoin_qt
